.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Andrew Bernard <andrew.bernard@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LYC 1 "April 25, 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lyc \- Lilypond compile server client
.SH SYNOPSIS
.B lyc
.RI [ options ] " files" ...
.SH DESCRIPTION
.B lyc
is the
.B lys
compile server client. It is used to submit files to the server for compilation.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR lys (1)
.br


