.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2016 Andrew Bernard <andrew.bernard@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LYS 1 "April 25, 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lys \- Lilypond compile server
.SH SYNOPSIS
.B lys
.RI [ options ]
.br
.SH DESCRIPTION
.B lys
is a compile server for lilypond, the open source music engraving program.
.PP
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR lyc (1)
.br
