Document: lys
Title: Debian lys Manual
Author: <insert document author here>
Abstract: This manual describes what lys is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lys/lys.sgml.gz

Format: postscript
Files: /usr/share/doc/lys/lys.ps.gz

Format: text
Files: /usr/share/doc/lys/lys.text.gz

Format: HTML
Index: /usr/share/doc/lys/html/index.html
Files: /usr/share/doc/lys/html/*.html
